// export const USER_PUSH_ID_SUCCESS = 'USER_PUSH_ID_SUCCESS';

export const USER_SETUP = 'USER_SETUP';
export const USER_SETUP_SUCCESS = 'USER_SETUP_SUCCESS';
export const USER_SETUP_FAILURE = 'USER_SETUP_FAILURE';

export const SUCCESS_POSITION = 'SUCCESS_POSITION';
export const FAILURE_POSITION = 'FAILURE_POSITION';

export const USER_PUSH_SUCCESS = 'USER_PUSH_SUCCESS';
export const USER_PUSH_FAILURE = 'USER_PUSH_FAILURE';
