// export const USER_PUSH_ID_SUCCESS = 'USER_PUSH_ID_SUCCESS';

export const USER_SETUP = 'USER_SETUP';
export const USER_CONNECTED = 'USER_CONNECTED';
export const USER_SETUP_SUCCESS = 'USER_SETUP_SUCCESS';
export const USER_SETUP_FAILURE = 'USER_SETUP_FAILURE';

export const SUCCESS_POSITION = 'SUCCESS_POSITION';
export const FAILURE_POSITION = 'FAILURE_POSITION';

export const USER_PUSH_SUCCESS = 'USER_PUSH_SUCCESS';
export const USER_PUSH_FAILURE = 'USER_PUSH_FAILURE';

export const SOCKET_CONNECTION_SUCCESS = 'SOCKET_CONNECTION_SUCCESS';
export const SOCKET_CONNECTION_FAILURE = 'SOCKET_CONNECTION_FAILURE';
export const SOCKET_CONNECTION_LOST = 'SOCKET_CONNECTION_LOST';
export const SOCKET_NEW_PINS = 'SOCKET_NEW_PINS';

export const GET_EVENTS_NEARBY_LOCATION = 'GET_EVENTS_NEARBY_LOCATION';

export const BEGIN_ADD_EVENT = 'BEGIN_ADD_EVENT';
export const SUBMIT_ADD_EVENT = 'SUBMIT_ADD_EVENT';
export const ADD_EVENT_SUCCESS = 'ADD_EVENT_SUCCESS';
export const ADD_EVENT_FAILURE = 'ADD_EVENT_FAILURE';
export const OPEN_EVENT = 'OPEN_EVENT';
export const BACK_FROM_OPEN_EVENT = 'BACK_FROM_OPEN_EVENT';

export const DELAY_HIDE_SPLASHSCREEN = 1000;

// export const LOUIS_API = 'http://75ca9186.ngrok.io';

export const LOUIS_API = 'http://163.172.29.197:3000';
